<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Patient extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Patient_model');
    } 

    /*
     * Listing of patient
     */
    function index()
    {
        $data['patient'] = $this->Patient_model->get_all_patient();
        
        $data['_view'] = 'patient/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new patient
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'private' => $this->input->post('private'),
				'lastname' => $this->input->post('lastname'),
				'firstname' => $this->input->post('firstname'),
				'middlename' => $this->input->post('middlename'),
				'prefix' => $this->input->post('prefix'),
				'suffix' => $this->input->post('suffix'),
				'ideographic' => $this->input->post('ideographic'),
				'phonetic' => $this->input->post('phonetic'),
				'birthdate' => $this->input->post('birthdate'),
				'birthtime' => $this->input->post('birthtime'),
				'sex' => $this->input->post('sex'),
				'otherid' => $this->input->post('otherid'),
				'othername' => $this->input->post('othername'),
				'ethnicgroup' => $this->input->post('ethnicgroup'),
				'institution' => $this->input->post('institution'),
				'address' => $this->input->post('address'),
				'age' => $this->input->post('age'),
				'height' => $this->input->post('height'),
				'weight' => $this->input->post('weight'),
				'occupation' => $this->input->post('occupation'),
				'lastaccess' => $this->input->post('lastaccess'),
				'patientmatchworklist' => $this->input->post('patientmatchworklist'),
				'issuer' => $this->input->post('issuer'),
				'speciesdescr' => $this->input->post('speciesdescr'),
				'sexneutered' => $this->input->post('sexneutered'),
				'breeddescr' => $this->input->post('breeddescr'),
				'respperson' => $this->input->post('respperson'),
				'resppersonrole' => $this->input->post('resppersonrole'),
				'resppersonorg' => $this->input->post('resppersonorg'),
				'charset' => $this->input->post('charset'),
				'comments' => $this->input->post('comments'),
				'history' => $this->input->post('history'),
            );
            
            $patient_id = $this->Patient_model->add_patient($params);
            redirect('patient/index');
        }
        else
        {            
            $data['_view'] = 'patient/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a patient
     */
    function edit($origid)
    {   
        // check if the patient exists before trying to edit it
        $data['patient'] = $this->Patient_model->get_patient($origid);
        
        if(isset($data['patient']['origid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'private' => $this->input->post('private'),
					'lastname' => $this->input->post('lastname'),
					'firstname' => $this->input->post('firstname'),
					'middlename' => $this->input->post('middlename'),
					'prefix' => $this->input->post('prefix'),
					'suffix' => $this->input->post('suffix'),
					'ideographic' => $this->input->post('ideographic'),
					'phonetic' => $this->input->post('phonetic'),
					'birthdate' => $this->input->post('birthdate'),
					'birthtime' => $this->input->post('birthtime'),
					'sex' => $this->input->post('sex'),
					'otherid' => $this->input->post('otherid'),
					'othername' => $this->input->post('othername'),
					'ethnicgroup' => $this->input->post('ethnicgroup'),
					'institution' => $this->input->post('institution'),
					'address' => $this->input->post('address'),
					'age' => $this->input->post('age'),
					'height' => $this->input->post('height'),
					'weight' => $this->input->post('weight'),
					'occupation' => $this->input->post('occupation'),
					'lastaccess' => $this->input->post('lastaccess'),
					'patientmatchworklist' => $this->input->post('patientmatchworklist'),
					'issuer' => $this->input->post('issuer'),
					'speciesdescr' => $this->input->post('speciesdescr'),
					'sexneutered' => $this->input->post('sexneutered'),
					'breeddescr' => $this->input->post('breeddescr'),
					'respperson' => $this->input->post('respperson'),
					'resppersonrole' => $this->input->post('resppersonrole'),
					'resppersonorg' => $this->input->post('resppersonorg'),
					'charset' => $this->input->post('charset'),
					'comments' => $this->input->post('comments'),
					'history' => $this->input->post('history'),
                );

                $this->Patient_model->update_patient($origid,$params);            
                redirect('patient/index');
            }
            else
            {
                $data['_view'] = 'patient/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The patient you are trying to edit does not exist.');
    } 

    /*
     * Deleting patient
     */
    function remove($origid)
    {
        $patient = $this->Patient_model->get_patient($origid);

        // check if the patient exists before trying to delete it
        if(isset($patient['origid']))
        {
            $this->Patient_model->delete_patient($origid);
            redirect('patient/index');
        }
        else
            show_error('The patient you are trying to delete does not exist.');
    }
    
}
