<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Study extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Study_model');
    } 

    /*
     * Listing of study
     */
    function index()
    {
        $data['study'] = $this->Study_model->get_all_study();
        
        $data['_view'] = 'study/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new study
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'private' => $this->input->post('private'),
				'matched' => $this->input->post('matched'),
				'id' => $this->input->post('id'),
				'patientid' => $this->input->post('patientid'),
				'studydate' => $this->input->post('studydate'),
				'studytime' => $this->input->post('studytime'),
				'accessionnum' => $this->input->post('accessionnum'),
				'modalities' => $this->input->post('modalities'),
				'referringphysician' => $this->input->post('referringphysician'),
				'description' => $this->input->post('description'),
				'readingphysician' => $this->input->post('readingphysician'),
				'admittingdiagnoses' => $this->input->post('admittingdiagnoses'),
				'interpretationauthor' => $this->input->post('interpretationauthor'),
				'received' => $this->input->post('received'),
				'sourceae' => $this->input->post('sourceae'),
				'reviewed' => $this->input->post('reviewed'),
				'verified' => $this->input->post('verified'),
				'compressed' => $this->input->post('compressed'),
				'studymatchworklist' => $this->input->post('studymatchworklist'),
				'requestingphysician' => $this->input->post('requestingphysician'),
				'updated' => $this->input->post('updated'),
				'REVIEWED_USER_ID' => $this->input->post('REVIEWED_USER_ID'),
				'REVIEWED_DATE' => $this->input->post('REVIEWED_DATE'),
				'mirthprocessed' => $this->input->post('mirthprocessed'),
				'is_critical' => $this->input->post('is_critical'),
				'critical_date' => $this->input->post('critical_date'),
				'mailed_date' => $this->input->post('mailed_date'),
				'has_attached_orders' => $this->input->post('has_attached_orders'),
				'text' => $this->input->post('text'),
				'notedate' => $this->input->post('notedate'),
				'username' => $this->input->post('username'),
				'has_tech_notes' => $this->input->post('has_tech_notes'),
				'processedITR' => $this->input->post('processedITR'),
				'fax_status' => $this->input->post('fax_status'),
            );
            
            $study_id = $this->Study_model->add_study($params);
            redirect('study/index');
        }
        else
        {            
            $data['_view'] = 'study/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a study
     */
    function edit($uuid)
    {   
        // check if the study exists before trying to edit it
        $data['study'] = $this->Study_model->get_study($uuid);
        
        if(isset($data['study']['uuid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'private' => $this->input->post('private'),
					'matched' => $this->input->post('matched'),
					'id' => $this->input->post('id'),
					'patientid' => $this->input->post('patientid'),
					'studydate' => $this->input->post('studydate'),
					'studytime' => $this->input->post('studytime'),
					'accessionnum' => $this->input->post('accessionnum'),
					'modalities' => $this->input->post('modalities'),
					'referringphysician' => $this->input->post('referringphysician'),
					'description' => $this->input->post('description'),
					'readingphysician' => $this->input->post('readingphysician'),
					'admittingdiagnoses' => $this->input->post('admittingdiagnoses'),
					'interpretationauthor' => $this->input->post('interpretationauthor'),
					'received' => $this->input->post('received'),
					'sourceae' => $this->input->post('sourceae'),
					'reviewed' => $this->input->post('reviewed'),
					'verified' => $this->input->post('verified'),
					'compressed' => $this->input->post('compressed'),
					'studymatchworklist' => $this->input->post('studymatchworklist'),
					'requestingphysician' => $this->input->post('requestingphysician'),
					'updated' => $this->input->post('updated'),
					'REVIEWED_USER_ID' => $this->input->post('REVIEWED_USER_ID'),
					'REVIEWED_DATE' => $this->input->post('REVIEWED_DATE'),
					'mirthprocessed' => $this->input->post('mirthprocessed'),
					'is_critical' => $this->input->post('is_critical'),
					'critical_date' => $this->input->post('critical_date'),
					'mailed_date' => $this->input->post('mailed_date'),
					'has_attached_orders' => $this->input->post('has_attached_orders'),
					'text' => $this->input->post('text'),
					'notedate' => $this->input->post('notedate'),
					'username' => $this->input->post('username'),
					'has_tech_notes' => $this->input->post('has_tech_notes'),
					'processedITR' => $this->input->post('processedITR'),
					'fax_status' => $this->input->post('fax_status'),
                );

                $this->Study_model->update_study($uuid,$params);            
                redirect('study/index');
            }
            else
            {
                $data['_view'] = 'study/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The study you are trying to edit does not exist.');
    } 

    /*
     * Deleting study
     */
    function remove($uuid)
    {
        $study = $this->Study_model->get_study($uuid);

        // check if the study exists before trying to delete it
        if(isset($study['uuid']))
        {
            $this->Study_model->delete_study($uuid);
            redirect('study/index');
        }
        else
            show_error('The study you are trying to delete does not exist.');
    }
    
}
