<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Patient_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get patient by origid
     */
    function get_patient($origid)
    {
        return $this->db->get_where('patient',array('origid'=>$origid))->row_array();
    }
        
    /*
     * Get all patient
     */
    function get_all_patient()
    {
        $this->db->order_by('origid', 'desc');
        return $this->db->get('patient')->result_array();
    }
        
    /*
     * function to add new patient
     */
    function add_patient($params)
    {
        $this->db->insert('patient',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update patient
     */
    function update_patient($origid,$params)
    {
        $this->db->where('origid',$origid);
        return $this->db->update('patient',$params);
    }
    
    /*
     * function to delete patient
     */
    function delete_patient($origid)
    {
        return $this->db->delete('patient',array('origid'=>$origid));
    }
}
