<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Study_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get study by uuid
     */
    function get_study($uuid)
    {
        return $this->db->get_where('study',array('uuid'=>$uuid))->row_array();
    }
        
    /*
     * Get all study
     */
    function get_all_study()
    {
        $this->db->order_by('uuid', 'desc');
        return $this->db->get('study')->result_array();
    }
        
    /*
     * function to add new study
     */
    function add_study($params)
    {
        $this->db->insert('study',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update study
     */
    function update_study($uuid,$params)
    {
        $this->db->where('uuid',$uuid);
        return $this->db->update('study',$params);
    }
    
    /*
     * function to delete study
     */
    function delete_study($uuid)
    {
        return $this->db->delete('study',array('uuid'=>$uuid));
    }
}
